### ISSUE TITLE
Segmentation Fault(core dumped)

### ISSUE THREAD

**Issue by wf-hahaha** [benchun123/object-based-loop-closure#1]
I'm running Ubuntu 20.04 with opencv 4.2. However, when initializing for optimization, there is always a Segmentation Fault. How can I solve this?
![21](https://github.com/benchun123/object-based-loop-closure/assets/26037040/e0d1617b-9a4d-4d1d-bab7-b3d78fc577f4)

**Comment by benchun123** [comment]
Hallo, 

Thanks for following this work. As I track the information, I think it may happen in the function: [Optimizer::GlobalBundleAdjustemnt](https://github.com/benchun123/object-based-loop-closure/blob/5c34aba41c8a12658815dd07b397e4cad51753e5/src/Tracking.cc#L796C5-L796C38)

So, I recommand to check your Eigen library or G2O library.  Some similar issues can be found at 
https://github.com/raulmur/ORB_SLAM2/issues/634
https://github.com/raulmur/ORB_SLAM2/issues/351
https://github.com/raulmur/ORB_SLAM2/issues/216

Besides, I have never tried opencv4.x, that is different from opencv3.x, I am not sure if my code works well with opencv4.x. 
If you still can not fix the problem, please write me again.

**Comment by wf-hahaha** [comment]
作者您好，还想咨询您下，如何制作yolo_txts，我想在自己录制的数据集上做实验，有木有生成yolo_txts文件的.py脚本，谢谢
