### ISSUE TITLE
检测不到回环以及物体方向问题

### ISSUE THREAD

**Issue by Geralt-of-winterfall** [benchun123/object-based-loop-closure#2]
作者你好，在跑你给定的demo出了问题。在你的视频里，最后的部分是检测到回环并校正轨迹，但我跑的效果却检测不到回环。
![2023-10-30 18-47-57屏幕截图](https://github.com/benchun123/object-based-loop-closure/assets/146155193/3a33e4bc-15e5-4c25-b3df-dfb18d53c7f8)
另外，物体检测上也有些问题，物体似乎不在地面上。
![2023-10-30 18-52-02屏幕截图](https://github.com/benchun123/object-based-loop-closure/assets/146155193/81eb5d3b-8e9d-42ce-b57a-88ce4155386c)

**Comment by benchun123** [comment]
您好，感谢您对相关工作的关注。

首先，这两个问题是有关联性的，如果物体检测不正确的话，回环检测也会收到影响。
其次，从截图上来看，检测的物体的方向并没有和地面对齐，我猜测是坐标系转换的问题，我在系统初始化的时候加入了[世界坐标系的转换](https://github.com/benchun123/object-based-loop-closure/blob/5c34aba41c8a12658815dd07b397e4cad51753e5/src/Tracking.cc#L825)，从而确保物体都是在地面上的，您可以参考一下，也可以点击“Draw Truth Camera” 去看相机的轨迹是否与地面平行。
最后，回环检测的鲁棒性有待多次验证，可重复实验。

祝好

**Comment by Geralt-of-winterfall** [comment]
> 您好，感谢您对相关工作的关注。
> 
> 首先，这两个问题是有关联性的，如果物体检测不正确的话，回环检测也会收到影响。 其次，从截图上来看，检测的物体的方向并没有和地面对齐，我猜测是坐标系转换的问题，我在系统初始化的时候加入了[世界坐标系的转换](https://github.com/benchun123/object-based-loop-closure/blob/5c34aba41c8a12658815dd07b397e4cad51753e5/src/Tracking.cc#L825)，从而确保物体都是在地面上的，您可以参考一下，也可以点击“Draw Truth Camera” 去看相机的轨迹是否与地面平行。 最后，回环检测的鲁棒性有待多次验证，可重复实验。
> 
> 祝好

您好，在您给定的Ground-Truth.txt文件中添加了一行，是保证了地面对齐的到世界坐标系的转换，这一行的位姿变换是如何获得的？
