### ISSUE TITLE
关于描述子中方向的问题

### ISSUE THREAD

**Issue by grdiv** [benchun123/object-based-loop-closure#4]
您好，请教一个问题，在计算描述子中角度问题时，坐标系是以物体为中心的局部坐标系吗？如果是的话，在匹配是怎么保证他们的坐标系与物体的朝向是一致的呢？谢谢

**Comment by benchun123** [comment]
您好，是这样。首先我们有了一个全局地图，所有的物体在这个地图坐标系下都有一个位姿。在计算描述子的时候，我们并没有关注物体的朝向，只是关注了物体之间的拓扑关系(相对位姿)：即你可以把物体当作一个点或者一个球体，看它在地图坐标系下各个方向有哪些物体，从而生成方向统计描述子，然后进行匹配。

**Comment by grdiv** [comment]
明白了，谢谢您。
